# This is a basic workflow to help you get started with Actions

name: ReleaseAWSS3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      #      - name: Get yarn cache directory path
      #        id: yarn-cache-dir-path
      #        run: echo "{name}=$(yarn cache dir)" >> $GITHUB_OUTPUT
      #
      #      - uses: actions/cache@v2
      #        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      #        with:
      #          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #          restore-keys: |
      #            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |
          corepack enable
          yarn set version stable
          yarn install --immutable

      - name: Build
        run: yarn build
        env:
          CI: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist s3://trade-axis --delete
